export const ACTION_TYPES = {
  // for allWorkoutsReducer
  SET_WORKOUTS: "SET_WORKOUT",
  CREATE_WORKOUT: "CREATE_WORKOUT",
  DELETE_WORKOUT: "DELETE_WORKOUT",
  UPDATE_WORKOUT: "UPDATE_WORKOUT",

  // for workoutReducer
  SET_INPUTS: "SET_INPUTS",
};
